### ISSUE TITLE
Am I missing other API endpoints?

### ISSUE THREAD

**Issue by amritg** [innofactor-pahkinat/talent2017#1]
My friend suggested me for this challenge. Somehow I can only find one API endpoint inside the given template `index.html` file. 
`$http.get('http://innofactor-talent-2017-challenge.azurewebsites.net/api/warnings')`
Is that the only endpoint resource we got to make the InfoGraph?

**Comment by innofactor-pahkinat** [comment]
Yes, that is the only endpoint resource

**Comment by jannef** [comment]
Feel free to combine the data with any other resources you can find, such as Google maps API etc.

**Comment by amritg** [comment]
@jannef @innofactor-pahkinat Thanks! :) I am thinking to add features from other services.
